-- Grant proper permissions to faithadmin
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO faithadmin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO faithadmin;
GRANT USAGE ON SCHEMA public TO faithadmin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO faithadmin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO faithadmin;